wmsubscription_mailchimp.audience.*:
    type: config_entity
    label: 'Mailchimp audience'
    mapping:
        id:
            type: string
            label: 'Audience'
        label:
            type: label
            label: 'Label'
